FROM golang:alpine

LABEL maintainer="Mr Beyond"

RUN apk update && apk add --no-cache git && apk add --no-cach bash && apk add build-base

RUN mkdir /app

WORKDIR /app

COPY . .

COPY .env .

RUN go get -d -v ./...

RUN go install -v ./...

# Build the Go app
RUN go build -o /build

# Expose port 8080 to the outside world
EXPOSE 8080


# Run the executable
# CMD [ "/build" ]

RUN go get github.com/githubnemo/CompileDaemon
RUN go install -mod=mod github.com/githubnemo/CompileDaemon

RUN go get -v golang.org/x/tools/gopls

ENTRYPOINT CompileDaemon --build="go build -a -buildvcs=false -installsuffix cgo -o main ." --command="./main"
